language: c

env:
 global:
  - EnableNuGetPackageRestore=true 

install:
  - sudo apt-get install mono-devel mono-gmcs

script:
 - mono --runtime=v4.0 .nuget/NuGet.exe restore
 - xbuild 
 - ./.ci/xunit.sh Spatial4n.Tests/bin/Debug/Spatial4n.Tests.dll

