language: c

env:
 global:
  - EnableNuGetPackageRestore=true 

install:
  - sudo add-apt-repository ppa:directhex/monoxide -y
  - sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs
  - mozroots --import --sync

script:
 - xbuild 
 - chmod +x .ci/xunit.sh
 - ./.ci/xunit.sh Spatial4n.Tests/bin/Debug/Spatial4n.Tests.dll

